name: Artifact Build

on: [push]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7

    - name: Set up JDK 21
      uses: actions/setup-java@v5.6.0
      with:
        distribution: temurin
        java-version: 21

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v5
      with:
        cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}
        cache-read-only: false

    - name: Build debug APK
      run: ./gradlew :androidApp:assembleAlphaDebug

    - name: Build signed sideload APK
      env:
        SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
        SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
        SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
      run: ./gradlew :androidApp:assembleAlphaSideload

    - name: Upload Debug Artifact
      uses: actions/upload-artifact@v7
      with:
        name: debug-build
        path: androidApp/build/outputs/apk/alpha/debug/*.apk

    - name: Upload Sideload Artifact
      uses: actions/upload-artifact@v7
      with:
        name: sideload-build
        path: androidApp/build/outputs/apk/alpha/sideload/*.apk
